/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package zibrathstudio;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author user
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
        content.removeAll();
        content.add(new mainDashboard());
        content.repaint();
        content.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnDashbord = new javax.swing.JButton();
        btnPesananMasuk = new javax.swing.JButton();
        btnLaporanKeuangan = new javax.swing.JButton();
        btnDataProduk = new javax.swing.JButton();
        btnAbout = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        btnDashbord.setBackground(new java.awt.Color(51, 51, 51));
        btnDashbord.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDashbord.setForeground(new java.awt.Color(255, 255, 255));
        btnDashbord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zibrathstudio/gambar/icons8-home-24.png"))); // NOI18N
        btnDashbord.setText("Dashboard");
        btnDashbord.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 1, 1));
        btnDashbord.setBorderPainted(false);
        btnDashbord.setFocusPainted(false);
        btnDashbord.setFocusable(false);
        btnDashbord.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDashbord.setOpaque(true);
        btnDashbord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashbordActionPerformed(evt);
            }
        });

        btnPesananMasuk.setBackground(new java.awt.Color(51, 51, 51));
        btnPesananMasuk.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPesananMasuk.setForeground(new java.awt.Color(255, 255, 255));
        btnPesananMasuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zibrathstudio/gambar/icons8-profitability-24.png"))); // NOI18N
        btnPesananMasuk.setText("Pesanan Masuk");
        btnPesananMasuk.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 1, 1));
        btnPesananMasuk.setBorderPainted(false);
        btnPesananMasuk.setFocusPainted(false);
        btnPesananMasuk.setFocusable(false);
        btnPesananMasuk.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPesananMasuk.setOpaque(true);
        btnPesananMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesananMasukActionPerformed(evt);
            }
        });

        btnLaporanKeuangan.setBackground(new java.awt.Color(51, 51, 51));
        btnLaporanKeuangan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLaporanKeuangan.setForeground(new java.awt.Color(255, 255, 255));
        btnLaporanKeuangan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zibrathstudio/gambar/icons8-purchase-order-23.png"))); // NOI18N
        btnLaporanKeuangan.setText("Laporan Keuangan");
        btnLaporanKeuangan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 1, 1));
        btnLaporanKeuangan.setBorderPainted(false);
        btnLaporanKeuangan.setFocusPainted(false);
        btnLaporanKeuangan.setFocusable(false);
        btnLaporanKeuangan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLaporanKeuangan.setOpaque(true);
        btnLaporanKeuangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanKeuanganActionPerformed(evt);
            }
        });

        btnDataProduk.setBackground(new java.awt.Color(51, 51, 51));
        btnDataProduk.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDataProduk.setForeground(new java.awt.Color(255, 255, 255));
        btnDataProduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zibrathstudio/gambar/icons8-product-24.png"))); // NOI18N
        btnDataProduk.setText("Data Produk");
        btnDataProduk.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 1, 1));
        btnDataProduk.setBorderPainted(false);
        btnDataProduk.setFocusPainted(false);
        btnDataProduk.setFocusable(false);
        btnDataProduk.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDataProduk.setOpaque(true);
        btnDataProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataProdukActionPerformed(evt);
            }
        });

        btnAbout.setBackground(new java.awt.Color(51, 51, 51));
        btnAbout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAbout.setForeground(new java.awt.Color(255, 255, 255));
        btnAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zibrathstudio/gambar/icons8-about-24 (1).png"))); // NOI18N
        btnAbout.setText("About");
        btnAbout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 1, 1));
        btnAbout.setBorderPainted(false);
        btnAbout.setFocusPainted(false);
        btnAbout.setFocusable(false);
        btnAbout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAbout.setOpaque(true);
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(51, 51, 51));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zibrathstudio/gambar/icons8-log-out-24.png"))); // NOI18N
        btnLogout.setText("Log Out");
        btnLogout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 1, 1));
        btnLogout.setBorderPainted(false);
        btnLogout.setFocusPainted(false);
        btnLogout.setFocusable(false);
        btnLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLogout.setOpaque(true);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zibrathstudio/gambar/logoZB.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDashbord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPesananMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnLaporanKeuangan, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
            .addComponent(btnDataProduk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAbout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDashbord, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnPesananMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnLaporanKeuangan, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnDataProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        content.setBackground(new java.awt.Color(0, 0, 0));
        content.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, 1018, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(content, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDataProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataProdukActionPerformed
        // TODO add your handling code here:
        content.removeAll();
        content.add(new panelDataProduk());
        content.repaint();
        content.revalidate();
    }//GEN-LAST:event_btnDataProdukActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        content.removeAll();
        content.add(new panelLogout());
        content.repaint();
        content.revalidate();
        
        boolean close = true;
        dlgLogout dlg = new dlgLogout(null, close);
        dlg.setTitle("Log Out");
        dlg.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        // TODO add your handling code here:
        content.removeAll();
        content.add(new panelAbout());
        content.repaint();
        content.revalidate();
    }//GEN-LAST:event_btnAboutActionPerformed

    private void btnDashbordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashbordActionPerformed
        // TODO add your handling code here:
        content.removeAll();
        content.add(new mainDashboard());
        content.repaint();
        content.revalidate();
    }//GEN-LAST:event_btnDashbordActionPerformed

    private void btnPesananMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesananMasukActionPerformed
        // TODO add your handling code here:
        content.removeAll();
        content.add(new panelPesanan());
        content.repaint();
        content.revalidate();
    }//GEN-LAST:event_btnPesananMasukActionPerformed

    private void btnLaporanKeuanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanKeuanganActionPerformed
        // TODO add your handling code here:
        content.removeAll();
        content.add(new panelLaporanKeuangan());
        content.repaint();
        content.revalidate();
    }//GEN-LAST:event_btnLaporanKeuanganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
            UIManager.put("Table.foreground", Color.white);
            UIManager.put("Table.background", new Color(51,51,51));
            UIManager.put("TableHeader.background", new Color(255,102,0));
            UIManager.put("TableHeader.foreground", Color.white);
        } catch (UnsupportedLookAndFeelException unsupportedLookAndFeelException) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnDashbord;
    private javax.swing.JButton btnDataProduk;
    private javax.swing.JButton btnLaporanKeuangan;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPesananMasuk;
    public static javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
