/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package zibrathstudio;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.text.DecimalFormat;
import static zibrathstudio.dashboard.content;

/**
 *
 * @author alia
 */
public class panelDetail extends javax.swing.JPanel {

//    untuk ambil id produk dari luar
            
    
    /**
     * Creates new form panelPesanan
     */
    public panelDetail() {
        initComponents();
        load_tabel_Detail();
    }
public void load_tabel_Detail() {
    String idpes = NoPes.getText();

    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Nama Produk");
    model.addColumn("Harga");
    model.addColumn("Qty");
    model.addColumn("Subtotal");

    String sql = "SELECT r.id_rincian, r.id_pesanan, p.nama_produk, r.qty, r.subtotal, ps.tgl_pesan, " +
                 "ps.status_pesanan, p.harga, ps.deadline, pel.nama_pelanggan, pel.no_wa, ps.total_harga " +
                 "FROM rincian_pesanan r " +
                 "JOIN pesanan ps ON r.id_pesanan = ps.id_pesanan " +
                 "JOIN produk p ON r.id_produk = p.id_produk " +
                 "JOIN pelanggan pel ON ps.id_pelanggan = pel.id_pelanggan " + 
                 "WHERE r.id_pesanan = ?";

    try {
        Connection conn = koneksi.konek();
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, idpes);

        ResultSet rs = ps.executeQuery();

        String status = "";
        String id = "";
        String deadline = "";
        String nama = "";
        String nomor = "";
        String total = "";

        while (rs.next()) {
            // Data untuk tabel detail
            String namaProduk = rs.getString("nama_produk");
            int harga = rs.getInt("harga");
            int qty = rs.getInt("qty");
            int subtotal = rs.getInt("subtotal");
            Object[] baris = {namaProduk, harga, qty, subtotal};
            model.addRow(baris);

            //jika variable status kosong maka diisi
            if (status.isEmpty()) {
                status = rs.getString("status_pesanan");
                id = rs.getString("id_pesanan");
                deadline = rs.getString("deadline");
                nama = rs.getString("nama_pelanggan");
                nomor = rs.getString("no_wa");
                total = rs.getString("total_harga");
            }
        }
//jika variable status tidak kosong maka set semua teks
        if (!status.isEmpty()) {
            NoPes.setText(id);
            NamPes.setText(nama);
            NoWa.setText(nomor);
            TgDeadline.setText(deadline);
            double Rp = Double.parseDouble(total);
            DecimalFormat df = new DecimalFormat("#,###,###");
            Total.setText("Rp." + df.format(Rp));
            
            if (status.equals("Belum Bayar")) {
                cStatus.removeAllItems();
                cStatus.addItem("Belum Bayar");
                cStatus.addItem("Sedang Diproses");
                cStatus.addItem("Selesai");
                cStatus.setSelectedItem("Belum Bayar");

            } else if (status.equals("Sedang Diproses")) {
                cStatus.removeAllItems();
                cStatus.addItem("Sedang Diproses");
                cStatus.addItem("Selesai");
                cStatus.setSelectedItem("Sedang Diproses");

            } else if (status.equals("Selesai")) {
                cStatus.removeAllItems();
                cStatus.addItem("Selesai");
                cStatus.setSelectedItem("Selesai");
            }
 
        }

        rs.close();
        ps.close();

    } catch (SQLException e) {
        e.printStackTrace();
        System.out.println("Error SQL: " + e.getMessage());
    }

    tbPesanan.setModel(model); 
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPesanan = new javax.swing.JTable();
        NoPes = new javax.swing.JLabel();
        NamPes = new javax.swing.JLabel();
        NoWa = new javax.swing.JLabel();
        TgDeadline = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        cStatus = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Detail Pesanan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        tbPesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbPesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPesananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbPesanan);

        NoPes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NoPes.setForeground(new java.awt.Color(255, 255, 255));
        NoPes.setText("No Pesanan");

        NamPes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NamPes.setForeground(new java.awt.Color(255, 255, 255));
        NamPes.setText("Nama Pemesan");

        NoWa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NoWa.setForeground(new java.awt.Color(255, 255, 255));
        NoWa.setText("NO WA");

        TgDeadline.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TgDeadline.setForeground(new java.awt.Color(255, 255, 255));
        TgDeadline.setText("tgl Deadline");

        Total.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Total.setForeground(new java.awt.Color(255, 255, 255));
        Total.setText("TotalHarga");

        cStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cStatusMouseClicked(evt);
            }
        });
        cStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cStatusActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Status Pemesanan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NoPes)
                    .addComponent(NamPes)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Total))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(NoWa)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TgDeadline))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(NoPes)
                .addGap(4, 4, 4)
                .addComponent(NamPes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NoWa)
                    .addComponent(TgDeadline))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Total)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void tbPesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPesananMouseClicked
        
    }//GEN-LAST:event_tbPesananMouseClicked

    private void cStatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cStatusMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cStatusMouseClicked

    private void cStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cStatusActionPerformed
        //merubah status pesanan
        if (cStatus.getSelectedItem().equals("Sedang Diproses")) {
            
            String sql = "UPDATE `pesanan` SET status_pesanan = ? WHERE id_pesanan = ?";
            Connection conn = koneksi.konek();
            try {
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, "Sedang Diproses");
                ps.setString(2, NoPes.getText());
                
                int rows = ps.executeUpdate();
                if (rows > 0) {
                    content.removeAll();
                    content.add(new panelPesanan());
                    content.repaint();
                    content.revalidate();
                    } else {
                    JOptionPane.showMessageDialog(null, "Error");
                }                
            } catch (SQLException sQLException) {
                System.out.println(sQLException);
            }

        } else if (cStatus.getSelectedItem().equals("Selesai")) {
            
            String sql = "UPDATE `pesanan` SET status_pesanan = ? WHERE id_pesanan = ?";
            Connection conn = koneksi.konek();
            try {
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, "Selesai");
                ps.setString(2, NoPes.getText());
                
                int rows = ps.executeUpdate();
                if (rows > 0) {
                    content.removeAll();
                    content.add(new panelPesanan());
                    content.repaint();
                    content.revalidate();
                    } else {
                    JOptionPane.showMessageDialog(null, "Error");
                }                
            } catch (SQLException sQLException) {
                System.out.println(sQLException);
            }

        }
        
    }//GEN-LAST:event_cStatusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NamPes;
    public static javax.swing.JLabel NoPes;
    private javax.swing.JLabel NoWa;
    private javax.swing.JLabel TgDeadline;
    private javax.swing.JLabel Total;
    private javax.swing.JComboBox<String> cStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbPesanan;
    // End of variables declaration//GEN-END:variables
}
